### ISSUE TITLE
accuracy of next-token and next-next-token

### ISSUE THREAD

**Issue by Dbxwz** [hemingkx/Spec-Bench#8]
Thanks for your great work!
I think draft token  acceptance rate has a great impact on the speedup ratio，but I didn't find any draft token acceptance rate comparison of different methods.  
Hoping for an update of Readme.md, similar to what is depicted in the figure below.
<img width="357" alt="截屏2024-05-22 14 40 13" src="https://github.com/hemingkx/Spec-Bench/assets/32608118/d5fbf25b-0bd9-45ff-a651-8630f3488bcf">

**Comment by hemingkx** [comment]
Thanks for your issue!

We plan to support the statistics of Token acceptance rate in the near future, as noted in our [roadmap](https://github.com/hemingkx/Spec-Bench/blob/main/ROADMAP.md). The implementation presents two main challenges:

1. **Draft Length Variability**: Each method has a different draft length, requiring specific modifications and examination of the source code for each method. This brings a considerable workload.
2. **Token Tree Drafts**: As mentioned in the [Eagle paper](http://arxiv.org/abs/2401.15077), token acceptance rate statistics are less applicable for token tree drafts because multiple tokens are sampled per location with only one accepted. Therefore, an appropriate evaluation framework should be designed to unify the statistical evaluation of various methods.

We are working on this and will provide updates soon. Stay tuned!
