### ISSUE TITLE
Error in sps inference

### ISSUE THREAD

**Issue by zankner** [hemingkx/Spec-Bench#9]
Running:

`python -m evaluation.inference_sps --drafter-path double7/vicuna-68m --model-path lmsys/vicuna-7b-v1.3 --model-id sps_1 --bench-name spec_bench --temperature 0.0 --dtype "float16"`

I get the error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/workdisk/zack/Spec-Bench/evaluation/inference_sps.py", line 125, in <module>
    run_eval(
  File "/mnt/workdisk/zack/Spec-Bench/evaluation/eval.py", line 54, in run_eval
    get_answers_func(
  File "/usr/lib/python3/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/workdisk/zack/Spec-Bench/evaluation/eval.py", line 111, in get_model_answers
    output_ids, new_token, step, accept_length_tree = forward_func(
  File "/mnt/workdisk/zack/Spec-Bench/evaluation/inference_sps.py", line 19, in sps_forward
    output_ids, idx, accept_length_list = model.generate(
ValueError: not enough values to unpack (expected 3, got 1)
```

**Comment by hemingkx** [comment]
We re-ran the codes and did not encounter this error. Could you check if your local code contains this [line](https://github.com/hemingkx/Spec-Bench/blob/main/evaluation/inference_sps.py#L91)?

**Comment by mklasby** [comment]
@hemingkx @zankner 
This is likely related to a `transfomers` library mismatch. In transformers 4.37.1, `GeneratorMixin` has a `assisted_decoding` member function that was renamed to `_assisted_decoding` in more recent releases. 
Master: https://github.com/huggingface/transformers/blob/main/src/transformers/generation/utils.py#L2001
4.37.1: https://github.com/huggingface/transformers/blob/v4.37.1/src/transformers/generation/utils.py

Of note, it appears that this function saw significant refactoring since release of SpecBench. I think it may be worthwhile to open an issue to refactor the model functions in this repo to match the refactored GeneratorMixin class.

**Comment by yanghu819** [comment]
Same issue

**Comment by hemingkx** [comment]
This issue was previously discussed in #23. As highlighted by @mklasby, we agree that the problem stems from a mismatch with the transformers library. We attempted to adapt Spec-Bench to the latest version of transformers but encountered challenges in resolving all errors without modifying the transformers package itself. As a result, we are maintaining the current stable implementation of Spec-Bench with transformers version 4.37.1.

That said, we welcome contributions! If you manage to successfully adapt Spec-Bench to work with the latest version of transformers, please feel free to submit a PR. We’d be happy to review it!
